remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

title: Konstantin Läufer
description: Professor of Computer Science, Loyola University Chicago

google_analytics: G-K59QLQZ07E
